use UNIVER;

--task1--
select GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY 
and FACULTY.FACULTY in ('’“Ë“')
group by rollup(GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY);

--task2--
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY
and FACULTY.FACULTY in ('’“Ë“')
group by cube(GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY);

--task3--
--part1--
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('’“Ë“')
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
union
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('»›‘')
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY;

--part2--
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('’“Ë“')
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
union all
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('»›‘')
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY;

--task4--
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('’“Ë“')
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
intersect
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('»›‘')
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY;

--task5--
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('’“Ë“')
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
except
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, avg(PROGRESS.NOTE) [mark]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('»›‘')
group by GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY;